-- Create an RSVPs table
CREATE TABLE IF NOT EXISTS public.rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  user_email TEXT NOT NULL,
  event_id INT NOT NULL,
  status TEXT CHECK (status IN ('attending', 'tentative', 'declined')) NOT NULL,
  UNIQUE(user_id, event_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read RSVPs
CREATE POLICY "Allow public read access" ON public.rsvps
  FOR SELECT USING (true);

-- Allow authenticated users to insert/update their own RSVPs
CREATE POLICY "Allow users to insert their own RSVP" ON public.rsvps
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own RSVP" ON public.rsvps
  FOR UPDATE USING (auth.uid() = user_id);
