load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

# gazelle:prefix github.com/gdowding/crewd

load("@bazel_env.bzl", "bazel_env")
load("@gazelle//:go_tools.bzl", "GO_TOOLS")

gazelle(name = "gazelle")

filegroup(
    name = "go_mod",
    srcs = [
        "go.mod",
        "go.sum",
    ],
    visibility = ["//:__subpackages__"],
)

go_library(
    name = "crewd_lib",
    srcs = ["main.go"],
    importpath = "github.com/gdowding/crewd",
    visibility = ["//visibility:private"],
    deps = [
        "//ent/ent",
        "//ent/ent/schedule",
        "@com_github_mattn_go_sqlite3//:go-sqlite3",
    ],
)

go_binary(
    name = "crewd",
    embed = [":crewd_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "crewd_test",
    srcs = ["crewd_test.go"],
    embed = [":crewd_lib"],
)

bazel_env(
    name = "env",
    tools = {
        "go": "@rules_go//go",
    } | GO_TOOLS,
)

# generate new ent src files. Need to do when anything in ent/schema changes
# need to figure out how to do this properly
# ent generate --target ent ./ent_schema/schema
