load("@bazel_env.bzl", "bazel_env")
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "crewd",
    srcs = ["src/main.rs"],
    visibility = ["//visibility:public"],
)

bazel_env(
    name = "env",
    toolchains = {
        "rust": "@rules_rust//rust/toolchain:current_rust_toolchain",
    },
    tools = {
        "cargo": "@rules_rust//tools/upstream_wrapper:cargo",
    },
)
