* what am I doing

Tool to manage crew roster and events that require crew. This is basically a resource and scheduling project as well as require some self serve aspects.

** I want to use org-mode to manage race data at least initially

It is easy to work with, for me, and has some flexibility.

** Here are some things I want to keep track of for a given race / day

- need to contact current crew and see who is available and can commit
- crew for each day
- crew positions
- need to plan delivery
- register
- race information
  - notice of race
  - sailing instructions
  - addendums
- conditions
  - wind
  - current
  - sea state
  - forcast
  - acutal
- results
  - should be able to download results

** weather api links from google search
https://stormglass.io/marine-weather/
https://api.windy.com
https://open-meteo.com/en/docs/marine-weather-api
https://www.weather.gov/documentation/services-web-api


* haskell implementation

I plan to implement in haskell and am planning using literate programming to create the code.

#+begin_src haskell :noweb yes :tangle "src/crewd.hs"
  <<crewd-hs>>
#+end_src


*** Preamble

#+begin_src haskell :noweb-ref crewd-hs  :noweb yes tangle yes
  {-# LANGUAGE OverloadedStrings #-}
  {-# LANGUAGE DeriveGeneric #-}

  module Main (main) where

  <<imports>>

  <<configuration>>

#+end_src

To keep things simple, I am defining the configuration information in the haskell source. Eventually this will be moved to an appropropriate location (file, environment variables, etc.).

#+begin_src haskell :noweb-ref configuration
  schedulePath = "/Users/gdowding/git/github/gdowding/crewd/schedule.csv"
  downloadDirectory = "/Users/gdowding/git/github/gdowding/crewd/results"
  raceInfo = "https://race.styc.org/race_info/"
#+end_src

** crewd.hs
:PROPERTIES:
:header-args: :noweb-ref crewd-hs
:END:


*** text / string primitive imports

#+begin_src haskell :noweb-ref imports
  import qualified Data.ByteString.Char8 as BC
  import qualified Data.Text as T

#+end_src
** Schedule

The schedule is made up of events. Starting simply events are races and are generally one day. There could be multiple races on that day. Or an event could span multiple days. In the simplest an event corresponds to a single race on a single day.

#+begin_src haskell :noweb yes :tangle "src/Schedule.hs"
  {-# LANGUAGE DeriveGeneric #-}

  module Schedule (Event(..), readEventCSV) where

  <<schedule-imports>>

  <<event>>

  <<event-csv>>

  <<event-parse-date>>

  <<event-read-csv>>
#+end_src

Import Schedule

#+begin_src haskell :noweb-ref imports
import Schedule
#+end_src

#+begin_src haskell :noweb-ref schedule-imports
  import qualified Data.Text as T
  import Data.Time.Calendar (Day)
  import GHC.Generics (Generic)
#+end_src

#+name: event
#+begin_src haskell
  data Event = Event
    { regatta    :: !T.Text
    , series     :: !T.Text
    , start_date :: !Day
    , race       :: !T.Text
    } deriving (Show, Generic)
#+end_src

I am storing the schedule in a CSV file.

#+begin_src haskell :noweb-ref schedule-imports
  import Data.Csv
  import Data.Time.Format (defaultTimeLocale,  parseTimeM)
  import qualified Data.ByteString as BS
  import qualified Data.ByteString.Char8 as BC
  import qualified Data.ByteString.Lazy as BL
  import qualified Data.Vector as V
#+end_src

This directive makes the Event type readable from a CSV file.

#+name: event-csv
#+begin_src haskell
  instance FromNamedRecord Event
#+end_src

Converting the =start_date= field to a day instance requires cusom parsing.

#+name: event-parse-date
#+begin_src haskell
  parseDate :: BS.ByteString -> Parser Day
  parseDate s =
    case parseTimeM True defaultTimeLocale "%Y-%m-%d" (BC.unpack s) of
      Just day -> pure day
      Nothing -> fail $ "Could not parse ISO-8601 date: " ++ BC.unpack s

  instance FromField Day where
    parseField = parseDate
#+end_src

Reading schedule and providing IO action to do the reading.

#+name: event-read-csv
#+begin_src haskell
  -- readEventCSV :: BL.ByteString -> IO (Either String (V.Vector Event))
  readEventCSV csvData = decodeByName csvData

#+end_src


** Results

Processing results involved downloading the raw data and saving it locally, then parsing to a tabular format and storing that locally in a CSV format. Here is the sequence to process a single event. It is implemented for Ballard Cup (see below), but this is the basis for getting results into a usable format.

#+begin_src haskell :noweb-ref imports
  import Text.HTML.TagSoup
  import System.Directory (createDirectoryIfMissing)
  import System.FilePath ((</>), (-<.>), dropDrive, takeFileName, takeDirectory)
  import Data.List (intercalate)
  import qualified Data.ByteString as BS
  import qualified Data.Text.IO as TIO
  import qualified Data.Text.Encoding as TE
  import Network.HTTP.Simple
#+end_src



#+begin_src haskell :noweb-ref crewd-hs
  -- fetch result. Save result to filePath and return body of response.

  fetchResult req filePath =
    do
      response <- httpBS req
      let bodyContent = getResponseBody response
      BS.writeFile filePath bodyContent
      return $ TE.decodeUtf8 bodyContent

  processResult event =
    do
      let url = getEvtUrl event
      req <- parseRequest url
      let filePath = localPath req
      -- Is this a race condition if multiple processes are attempting to create directory at same time?
      -- or is it thread safe?
      createDirectoryIfMissing True $ takeDirectory filePath
      -- either get body from url or read from file.
      respBody <- fetchResult req filePath
      -- respBody <- TIO.readFile filePath
      let tags = parseTags $ T.unpack  respBody
      let classes = partitions (~== ("<p class=classtitle>" :: String)) tags
      let results = flattenSnd $ map getResults classes
      let resultString = intercalate "\n" $ map rowToCsv results
      let csvPath = filePath -<.> ".csv"
      putStrLn filePath
      putStrLn csvPath
      -- putStrLn resultString
      TIO.writeFile csvPath $ T.pack resultString

#+end_src

The way I decided to return the processing of the Ballard Cup results is to return a tuple of =(header, data)= where header is a list of headings and data is a list of lists containing the data for the results. When writing out the file, I only want one header for the entire file. =flattenSnd= flattens the results for each class and throws away the header.

#+begin_src haskell :noweb-ref crewd-hs
  flattenSnd results =
    let
      (headList, _):_ = results
      resultData = concatMap snd results
    in
      headList:resultData

#+end_src

*** Ballard Cup

I am starting with Ballard Cup since this is the series that I am currently participating in.

The results are available from a static web site. It is pretty straight forward to generate the URL to the results based on the event.

The main result page gives the completed races for the series broken down by each class.

https://race.styc.org/race_info/Ballard_Cup/SeriesIII/2026/series.htm?t=326760

This page has links to individual race results. I prefer this page since it has the timing information. This is useful for tracking progress through the series.

Race 1
https://race.styc.org/race_info/Ballard_Cup/SeriesIII/2026/race1.htm

Race 2
https://race.styc.org/race_info/Ballard_Cup/SeriesIII/2026/race2.htm


Here is the implementation of converting an event to a URl that can be used to download the results. This applies only to Ballard Cup events. The function =raceInfo= is defined in the configuration section.

#+begin_src haskell :noweb-ref imports
  import Data.Time.Calendar (toGregorian)
#+end_src

#+begin_src haskell :noweb-ref crewd-hs
  getEvtUrl :: Event -> String
  getEvtUrl Event {regatta = r, series = s, start_date = d, race = n} =
    raceInfo ++ regatta' ++ "/" ++ series' ++ "/" ++ year ++ "/" ++ "race" ++ race' ++ ".htm"
    where
      regatta' = map (\x -> if x == ' ' then '_' else x) $ T.unpack r
      (y, _, _) = toGregorian d
      year = show y
      series'  = "Series" ++ T.unpack s
      race' = T.unpack n

#+end_src

Getting results for a single class of a Ballard Cup. The classes are extracted in =processResult= the resulting list is mapped over =getResults=. The return type is a tuple of =(header, data)=. I'm not totally happy with that, but it seems like the right thing to return when zoomed into what this function is responsible for.

#+begin_src haskell
let classes = partitions (~== ("<p class=classtitle>" :: String)) tags
#+end_src

#+begin_src haskell :noweb-ref crewd-hs
getResults :: [Tag String] -> ([String], [[String]])
getResults r =
  let (cHead, cData) = getHeadFromResult r
      (dHead, dValues) = getValuesFromResult r
      classDataValues = map (\d -> cData ++ d) dValues
  in
    (cHead ++ dHead, classDataValues)

#+end_src

Get the headings. TODO: include example heading of what is being parsed.

#+begin_src haskell :noweb-ref imports
import Data.List.Split (splitOn)
#+end_src

#+begin_src haskell :noweb-ref crewd-hs
  classFromSect s = unwords . words . innerText . drop 1  $ take 2 s

  -- get heading data from single class result
  getHeadFromResult r =
       let classTitle = classFromSect r
           -- split into fields and remove separators
           classFields = splitOn " - " classTitle
           fields = map (\h -> (fst h, dropWhile (\c -> c == ':' || c == ' ') $ snd h)) $ map (break (== ':')) classFields
           -- transpose from [(field1, data1) ...] to [[field1, ...], [data1, ...]
           headings =  map (escapeCSV . fst) fields
           values = map (escapeCSV . snd) fields
           -- clean up the second column by adding a field name and using the supplied field name as data.
           description = headings !! 1
           h = (\(x:_:xs) -> x : "Description" : xs) headings
           d = (\(x:_:xs) -> x : description : xs) values
       in
           (h, d)

#+end_src

Get values from result

#+begin_src haskell :noweb-ref imports
import Data.Char (isSpace)
#+end_src

#+begin_src haskell :noweb-ref crewd-hs
  getRowData row = map (escapeCSV . trimEnd . unwords . (map fromTagText)) $ map (filter isTagText) row

  getDataHeadings th = escapeCSV . unwords $ filter (not . null) $ map (filter (not . isSpace)) $ map fromTagText $ filter isTagText th

  getValuesFromResult :: [Tag [Char]] -> ([String], [[String]])
  getValuesFromResult r =
    let
      block = takeWhile (~/= ("</table>" :: String)) r
      rows = partitions (~== ("<tr>" :: String)) block
      th = partitions (~== ("<th>" :: String)) $ head rows
      dataHeadings = map getDataHeadings th
      tdPart = map (partitions (~== ("<td>" :: String))) $ drop 1 rows
      dataValues = map getRowData tdPart
    in
      (dataHeadings, dataValues)


#+end_src

*** String functions

#+begin_src haskell :noweb-ref imports
import Data.List (dropWhileEnd)
#+end_src

#+begin_src haskell :noweb-ref crewd-hs
trimEnd :: String -> String
trimEnd = dropWhileEnd isSpace

#+end_src

*** CSV Output Support

Convert a row (list of strings) to a single CSV string. Possibly this is where I could perform =escapeCSV=

#+begin_src haskell :noweb-ref crewd-hs
rowToCsv :: [String] -> String
rowToCsv = intercalate ","

#+end_src

Need to handle embeded ',' and '"'. I'm escaping pretty early on when processing the data. I would prefer to do it later as when outputing to CSV. Currently this is being called as the data is parsed.

#+begin_src haskell :noweb-ref crewd-hs
  escapeCSV :: [Char] -> [Char]
  escapeCSV = wrapDoubleQuote . escapeQuotes
    where
      wrapDoubleQuote s' = "\"" ++ s' ++ "\""
      escapeQuotes = concatMap (\c -> if c == '"' then "\"\"" else [c])

#+end_src

*** Local File Management

Convert a request to a local path. The idea is to use store files in the a directory that is named as download_dir/host/urlpath/

#+begin_src haskell :noweb-ref imports
import qualified Network.HTTP.Client as CL
#+end_src

#+begin_src haskell :noweb-ref crewd-hs
localPath req =
  downloadDirectory </> filePath
  where
    reqHost = BC.unpack $ CL.host req
    reqPath = BC.unpack $ CL.path req
    filePath = reqHost </> dropDrive reqPath

#+end_src


** Pipeline

#+begin_src haskell :noweb-ref imports
import Data.Time.Clock (getCurrentTime, utctDay)
#+end_src

#+begin_src haskell :noweb-ref crewd-hs
  -- Only process events that have already occoured.
  runPipeline :: V.Vector Event -> IO ()
  runPipeline events = do
    currentDay <- utctDay <$> getCurrentTime
    let pastEvents = V.filter (\e -> start_date e < currentDay) events
    V.forM_ pastEvents processResult
    putStrLn "finish"

#+end_src

** Main

The main function runs a schedule then calls the pipeline to download results, parse them, then store the parsed results in a CSV.

#+begin_src haskell :noweb-ref imports
  import qualified Data.Vector as V
  import qualified Data.ByteString.Lazy as BL
  import System.Exit as Exit

#+end_src

Read in the schedule. This mud be done within a do block.

#+begin_src haskell :noweb-ref crewd-hs
  main :: IO ()
  main = do
    csvData <- BL.readFile schedulePath
    case readEventCSV csvData of
      Left err -> Exit.die err
      Right(_, v) -> runPipeline (v :: V.Vector Event)

#+end_src


* http server
:PROPERTIES:
:GPTEL_TOPIC: http-server
:END:

#+begin_src haskell :noweb yes :tangle "src/screwd.hs"
  {-# LANGUAGE DataKinds #-}
  {-# LANGUAGE TypeOperators #-}

  module Main where

  import Data.Aeson
  import Data.Text
  import Data.Time.Calendar
  import GHC.Generics
  import Network.Wai
  import Network.Wai.Handler.Warp
  import Servant
  <<screwd-imports>>


  type ScheduleAPI = "schedule" :> Get '[JSON] [Event]

  instance ToJSON Event

  server :: [Event] -> Server ScheduleAPI
  server = return

  scheduleAPI :: Proxy ScheduleAPI
  scheduleAPI = Proxy

  app :: [Event] -> Application
  app events = serve scheduleAPI (server events)

  <<configuration>>

  <<screwd-main>>
#+end_src

Now I want to read in the schedule and serve that as JSON.

First import the Schedule module and other required modules.

#+name: screwd-imports
#+begin_src haskell
  import qualified Data.Vector as V
  import qualified Data.ByteString.Lazy as BL
  import System.Exit as Exit
  import Schedule
#+end_src


#+name: screwd-main
#+begin_src haskell
runServer schedData = do
  (_, events) <- readEventCSV schedData
  return $ run 8081 (app (V.toList events))


main :: IO ()
main = do
  csvData <- BL.readFile schedulePath
  case runServer csvData of
    Left err -> Exit.die err
    Right io -> io
#+end_src


How do I read in a file schedule.csv and return the data in the server function. I already have a module that will read the CSV file into a Vector of Event

#+begin_reasoning
**Initiating the Task**

I'm now diving into the user's request. My focus is on loading `schedule.csv` into a `Vector Event` data structure. I'm taking stock of the existing `Schedule` module for CSV parsing, to leverage that effectively.


**Refining Data Access**

I've revised the API, ensuring it aligns with `ScheduleAPI` instead of `UserAPI`. I'm now exploring two distinct methods for file access. Option 1 involves loading CSV data at startup, passing it to the server. Alternatively, Option 2 will read the CSV dynamically within the server handler using `liftIO`, which is suitable for changing data. I'm leaning toward Option 1, for static data, but I've drafted code changes for both approaches.



#+end_reasoning

To serve the CSV data, you have two options: read the file on every request, or read it once at startup (recommended for performance).

Since your API expects a list (=[Event]=) but your module returns a =Vector Event=, you will also need to convert it using =Data.Vector.toList=.

*** Option 1: Read once at startup (Recommended)
Pass the loaded data from =main= into your =server= function.

#+begin_src haskell
import qualified Data.Vector as V

-- 1. Update server to accept the events
server :: [Event] -> Server ScheduleAPI
server events = return events

-- 2. Update app to accept and pass the events
app :: [Event] -> Application
app events = serve scheduleAPI (server events)

-- 3. Read the file in main and pass it down
main :: IO ()
main = do
  -- Replace `readEvents` with your actual Schedule module function
  eventsVec <- readEvents "schedule.csv"
  let events = V.toList eventsVec
  run 8081 (app events)
#+end_src


* frontend
:PROPERTIES:
:GPTEL_TOPIC: react-frontend
:END:

** refactor to load schedule from local server

Eventually I want to rewrite this in Elm or Haskell.

#+begin_src js :tangle "windward-racing/src/App.jsx"
  import React, { useState, useEffect, useRef, useCallback } from 'react';
  import { Users, ExternalLink, CheckCircle, XCircle, HelpCircle, Filter, LogIn, LogOut, User, Edit3, Loader2 } from 'lucide-react';
  import AuthModal from './components/AuthModal.jsx';
  import ProfileModal from './components/ProfileModal.jsx';
  import { supabase } from './lib/supabase.js';

  export default function App() {
    // events
    // const [events] = useState(SCHEDULE_DATA);
    const [schedule, SetSchedule] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    // Attendence
    const [rsvpState, setRsvpState] = useState({});
    const [attendeesByEvent, setAttendeesByEvent] = useState({});
    const [savingEventId, setSavingEventId] = useState(null);
    const [showAllEvents, setShowAllEvents] = useState(false);
    const [isAuthOpen, setIsAuthOpen] = useState(false);
    const [isProfileOpen, setIsProfileOpen] = useState(false);
    const [currentUser, setCurrentUser] = useState(null);

    const isFetchingRef = useRef(false);

    const getDisplayName = (user) => {
      return user?.user_metadata?.username || user?.email?.split('@')[0] || 'Crew';
    };

    useEffect(() => {
        const url = 'localhost:8081/schedule';

        fetch(url)
  	  .then((response) => {
  	      if (!response.ok) {
  		  throw new Error('Network response was not ok');
  	      }
  	      return response.json();
  	  })
  	  .then((data) => {
  	      setSchedule(data);
  	      setLoading(false);
  	  })
  	  .catch((err) => {
  	      setError(err);
  	      setLoading(false);
  	  });
    }, []);


    // Fetch RSVPs from database without setting triggering dependencies
    const loadRsvps = useCallback(async (userId) => {
      if (isFetchingRef.current) return;
      isFetchingRef.current = true;

      try {
        const { data, error } = await supabase.from('rsvps').select('*');
        if (!error && data) {
          const userMap = {};
          const attendeesMap = {};

          data.forEach(item => {
            if (userId && item.user_id === userId) {
              userMap[item.event_id] = item.status;
            }

            if (item.status === 'attending') {
              if (!attendeesMap[item.event_id]) {
                attendeesMap[item.event_id] = [];
              }
              const name = item.username || item.user_email?.split('@')[0] || 'Crew';
              if (!attendeesMap[item.event_id].includes(name)) {
                attendeesMap[item.event_id].push(name);
              }
            }
          });

          setRsvpState(userMap);
          setAttendeesByEvent(attendeesMap);
        }
      } catch (e) {
        console.error('Failed to load RSVPs', e);
      } finally {
        isFetchingRef.current = false;
      }
    }, []);

    // Run Auth check ONCE on initial mount
    useEffect(() => {
      let isMounted = true;

      async function initAuth() {
        const { data: { session } } = await supabase.auth.getSession();
        if (isMounted) {
          const user = session?.user ?? null;
          setCurrentUser(user);
          loadRsvps(user?.id);
        }
      }

      initAuth();

      const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
        if (isMounted) {
          const user = session?.user ?? null;
          setCurrentUser(user);
          loadRsvps(user?.id);
        }
      });

      return () => {
        isMounted = false;
        subscription.unsubscribe();
      };
    }, []); // Strictly empty dependency array to prevent loops

    const handleRsvp = async (eventId, status) => {
      if (!currentUser) {
        setIsAuthOpen(true);
        return;
      }

      const activeUsername = getDisplayName(currentUser);
      setSavingEventId(eventId);

      // 1. Local state update
      setRsvpState(prev => ({ ...prev, [eventId]: status }));
      setAttendeesByEvent(prev => {
        const currentList = prev[eventId] || [];
        if (status === 'attending') {
          return {
            ...prev,
            [eventId]: Array.from(new Set([...currentList, activeUsername]))
          };
        } else {
          return {
            ...prev,
            [eventId]: currentList.filter(name => name !== activeUsername)
          };
        }
      });

      // 2. Database upsert
      try {
        await supabase
          .from('rsvps')
          .upsert({
            user_id: currentUser.id,
            user_email: currentUser.email,
            username: activeUsername,
            event_id: eventId,
            status: status
          }, { onConflict: 'user_id,event_id' });
      } catch (err) {
        console.error('RSVP save error:', err);
      } finally {
        setSavingEventId(null);
      }
    };

    const handleLogout = async () => {
      await supabase.auth.signOut();
      setCurrentUser(null);
      setRsvpState({});
    };

    const today = new Date();
    const fourWeeksLater = new Date(today);
    fourWeeksLater.setDate(today.getDate() + 28);

    const displayedEvents = showAllEvents
      ? events
      : events.filter(evt => {
          const eventDate = new Date(evt.startDate);
          return eventDate >= today && eventDate <= fourWeeksLater;
        });

    return (
      <div className="min-h-screen bg-slate-900 text-slate-100 font-sans">
        <header className="bg-slate-800 border-b border-slate-700 px-6 py-4 flex justify-between items-center sticky top-0 z-10">
          <div className="flex items-center space-x-3">
            <h1 className="text-xl font-bold tracking-wide text-white">IRIE RACING 2026</h1>
            <span className="bg-orange-500/20 text-orange-400 text-xs px-2.5 py-0.5 rounded-full border border-orange-500/30 font-semibold">
              {displayedEvents.length} {showAllEvents ? 'Total Events' : 'Next 4 Weeks'}
            </span>
          </div>

          <div>
            {currentUser ? (
              <div className="flex items-center space-x-3">
                <button
                  onClick={() => setIsProfileOpen(true)}
                  className="text-xs text-slate-300 flex items-center gap-1.5 bg-slate-700/60 hover:bg-slate-700 px-3 py-1.5 rounded-full border border-slate-600 transition"
                >
                  <User className="w-3.5 h-3.5 text-orange-400" />
                  <span>{getDisplayName(currentUser)}</span>
                  <Edit3 className="w-3 h-3 text-slate-400 ml-1" />
                </button>
                <button
                  onClick={handleLogout}
                  className="flex items-center space-x-1 bg-slate-700 hover:bg-slate-600 text-xs font-semibold px-3 py-1.5 rounded transition text-slate-200"
                >
                  <LogOut className="w-3.5 h-3.5" />
                  <span>Logout</span>
                </button>
              </div>
            ) : (
              <button
                onClick={() => setIsAuthOpen(true)}
                className="flex items-center space-x-1.5 bg-orange-500 hover:bg-orange-600 text-white text-xs font-semibold px-3.5 py-1.5 rounded transition"
              >
                <LogIn className="w-3.5 h-3.5" />
                <span>Crew Login</span>
              </button>
            )}
          </div>
        </header>

        <main className="p-6 max-w-4xl mx-auto space-y-6">
          {/* Filter Toggle Toolbar */}
          <div className="flex justify-between items-center pt-2">
            <div>
              <h2 className="text-lg font-bold text-white">
                {showAllEvents ? 'All 2026 Regattas' : 'Upcoming Races (Next 4 Weeks)'}
              </h2>
              <p className="text-xs text-slate-400">
                {showAllEvents ? 'Showing complete season' : `Filtered: ${today.toISOString().split('T')[0]} to ${fourWeeksLater.toISOString().split('T')[0]}`}
              </p>
            </div>

            <button
              onClick={() => setShowAllEvents(!showAllEvents)}
              className="flex items-center space-x-2 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-xs font-semibold px-3 py-2 rounded-md transition text-slate-200"
            >
              <Filter className="w-3.5 h-3.5 text-orange-400" />
              <span>{showAllEvents ? 'Show Next 4 Weeks Only' : 'Show Full Season (54 Races)'}</span>
            </button>
          </div>

          <div className="flex flex-col space-y-4">
            {displayedEvents.map((evt) => {
              const currentStatus = rsvpState[evt.id] || 'pending';
              const dbAttendees = attendeesByEvent[evt.id] || [];
              const combinedCrew = Array.from(new Set([...(evt.crew || []), ...dbAttendees]));
              const isSaving = savingEventId === evt.id;

  	    // TODO: refactor to use json schedule
              return (
                <div key={evt.id} className="bg-slate-800 p-5 rounded-lg border border-slate-700 hover:border-slate-600 transition flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="flex-1 space-y-1">
                    <div className="flex items-center space-x-2">
                      <span className="text-xs uppercase font-bold tracking-wider text-orange-400">
                        {evt.series}
                      </span>
                      <span className="text-[10px] bg-slate-700 text-slate-300 px-2 py-0.5 rounded uppercase font-semibold">
                        {evt.sponsor}
                      </span>
                    </div>

                    <h3 className="text-lg font-semibold text-white">{evt.race}</h3>

                    <p className="text-xs text-slate-400">
                      📅 {evt.startDate} {evt.endDate !== evt.startDate ? `to ${evt.endDate}` : ''}
                    </p>

                    {evt.notes && (
                      <p className="text-xs text-amber-400 bg-amber-500/10 px-2.5 py-1 rounded border border-amber-500/20 inline-block mt-1">
                        ⚠️ {evt.notes}
                      </p>
                    )}
                  </div>


  		  {/* Middle Block: Assigned Crew (Protected) */}
  		  <div className="md:w-1/3">
  		      <p className="text-xs font-semibold text-slate-400 mb-1.5 flex items-center gap-1">
  			  <Users className="w-3.5 h-3.5" /> Assigned Crew:
  		      </p>

  		      {currentUser ? (
  			  /* Logged In: Show Live Combined Roster */
  			  combinedCrew.length > 0 ? (
  			      <div className="flex flex-wrap gap-1">
  				  {combinedCrew.map((member, idx) => {
  				      const isDbUser = dbAttendees.includes(member);
  				      return (
  					  <span
  					      key={idx}
  					      className={`text-[11px] px-2 py-0.5 rounded ${
                  isDbUser
                    ? 'bg-emerald-950/80 text-emerald-300 border border-emerald-700/50 font-medium'
                    : 'bg-slate-700/80 text-slate-200'
                }`}
  					  >
  					      {member}
  					  </span>
  				      );
  				  })}
  			      </div>
  			  ) : (
  			      <span className="text-xs text-slate-500">No crew assigned yet</span>
  			  )
  		      ) : (
  			  /* Logged Out: Privacy Protection Message */
  			  <button
  			      onClick={() => setIsAuthOpen(true)}
  			      className="text-xs text-slate-500 hover:text-orange-400 border border-dashed border-slate-700 hover:border-orange-500/50 rounded px-2.5 py-1.5 transition text-left block w-full"
  			  >
  			      🔒 Log in to view crew roster ({combinedCrew.length})
  			  </button>
  		      )}
  		  </div>


                  <div className="flex md:flex-col items-center md:items-end justify-between md:justify-center border-t md:border-t-0 md:border-l border-slate-700/60 pt-3 md:pt-0 md:pl-5 gap-3">
                    <div className="flex items-center space-x-1.5 relative">
                      {isSaving && (
                        <Loader2 className="w-3.5 h-3.5 text-orange-400 animate-spin absolute -left-5" />
                      )}
                      <button
                        onClick={() => handleRsvp(evt.id, 'attending')}
                        disabled={isSaving}
                        className={`p-2 rounded transition ${
                          currentStatus === 'attending' ? 'bg-emerald-600 text-white' : 'bg-slate-700 text-slate-400 hover:text-white'
                        }`}
                        title="Attending"
                      >
                        <CheckCircle className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleRsvp(evt.id, 'tentative')}
                        disabled={isSaving}
                        className={`p-2 rounded transition ${
                          currentStatus === 'tentative' ? 'bg-amber-600 text-white' : 'bg-slate-700 text-slate-400 hover:text-white'
                        }`}
                        title="Tentative"
                      >
                        <HelpCircle className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleRsvp(evt.id, 'declined')}
                        disabled={isSaving}
                        className={`p-2 rounded transition ${
                          currentStatus === 'declined' ? 'bg-rose-600 text-white' : 'bg-slate-700 text-slate-400 hover:text-white'
                        }`}
                        title="Decline"
                      >
                        <XCircle className="w-4 h-4" />
                      </button>
                    </div>

                    {evt.eventUrl ? (
                      <a
                        href={evt.eventUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="text-xs text-sky-400 hover:underline flex items-center gap-1"
                      >
                        Event Page <ExternalLink className="w-3 h-3" />
                      </a>
                    ) : (
                      <span className="text-xs text-slate-500">No URL</span>
                    )}
                  </div>

                </div>
              );
            })}
          </div>
        </main>

        <AuthModal
          isOpen={isAuthOpen}
          onClose={() => setIsAuthOpen(false)}
          onSessionChange={(user) => {
            setCurrentUser(user);
            loadRsvps(user?.id);
          }}
        />

        <ProfileModal
          isOpen={isProfileOpen}
          onClose={() => setIsProfileOpen(false)}
          currentUser={currentUser}
          onProfileUpdated={(updatedUser) => {
            setCurrentUser(updatedUser);
            loadRsvps(updatedUser?.id);
          }}
        />
      </div>
    );
  }

#+end_src


** load schedule from url

I am working on a react front end. I want to refactor the way I load the schedule. Currently I am importing it from a file "schedule.js". I want to change it to load the schedule from the URL

#+begin_reasoning
**Defining the Approach**

I'm currently focused on the overarching goal: refactoring a React frontend. The primary aim is to load a schedule from a URL rather than a local file. To achieve this, I'm identifying the core technologies involved, like React, JavaScript/TypeScript, and the `fetch` API. Using `fetch` seems ideal due to its built-in and standard nature.


**Refining the Logic**

I've been thinking about the practical implementation using React Hooks, specifically `useEffect` and `useState`. I plan to use state variables for the schedule data itself, alongside states for loading and error conditions. The `useEffect` hook will handle fetching the schedule data from a specified URL upon component mounting. I'm focusing on handling the asynchronous nature of `fetch`, considering error handling and state updates in response to the request's status.



#+end_reasoning

Here is how you can refactor your React component to fetch the schedule from a URL using =useState= and =useEffect=.

Replace your static import with the following:

#+begin_src javascript
  import React, { useState, useEffect } from 'react';

  export default function ScheduleComponent() {
    const [schedule, setSchedule] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
      // Replace with your actual URL
      const url = 'https://api.yoursite.com/schedule.json';

      fetch(url)
        .then((response) => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then((data) => {
          setSchedule(data);
          setLoading(false);
        })
        .catch((err) => {
          setError(err);
          setLoading(false);
        });
    }, []); // Empty array ensures this runs once on mount

    if (loading) return <div>Loading schedule...</div>;
    if (error) return <div>Error loading schedule: {error.message}</div>;

    return (
      <div>
        {/* Render your schedule data here */}
        <pre>{JSON.stringify(schedule, null, 2)}</pre>
      </div>
    );
  }
#+end_src

*Key changes:*
1. Removed =import schedule from './schedule.js'=.
2. Added =useState= to hold the parsed JSON data, loading state, and error state.
3. Added =useEffect= to trigger the =fetch= request as soon as the component mounts. localhost:8081/schedule



** switch to functional front end

- giving miso a try

  https://haskell-miso.org/docs/installation

  In [[file:miso-sampler]]


this is quite heavy to get up and running. I think I'm going to give ELM a try

** install elm with nix

 I have an existing flake.nix file that is configured to build a backend for a project. I want to build the frontend using ELM. How do I add ELM to this flake.nix file?


#+begin_reasoning
**Considering Elm Integration**

I'm currently focused on the overarching goal: integrating Elm into the existing `flake.nix` environment. My immediate task involves understanding where Elm fits best – as a shell dependency or build tool for the frontend. I need to figure out the most effective integration approach given the existing Haskell and npm components.


**Integrating Elm Dependencies**

I've been examining the current `flake.nix` structure, which leverages `haskell.nix` and `flake-utils` with overlays, and the `buildNpmPackage` setup for the frontend. My focus is on determining the optimal placement for Elm's dependencies. I'm leaning toward incorporating Elm tools directly into the development shell through `shell.buildInputs`, since it is generated by `hixProject`. This method seems the most direct. Also, there's the question of whether or how elm may be called within the npm scripts.


**Implementing Elm in Build**

I'm now formulating concrete changes to integrate Elm effectively. My approach includes adding `elmPackages.elm` to both the development shell, using `buildInputs`, and the `nativeBuildInputs` of the `frontend` derivation within `buildNpmPackage`. The dev shell configuration will include `elmPackages.elm`, `elm-format`, and `elm-language-server`, to facilitate Elm development. The build environment needs `elm` in `nativeBuildInputs`, to support `elm` and `elm-format`, thereby resolving the availability for `elm` within `buildNpmPackage`.



#+end_reasoning

To add Elm to your project, you need to make it available in two places: your development shell (for local coding) and your frontend build derivation (so NPM can compile the Elm code).

Update your =flake.nix= with these two additions:

1. Add Elm packages to your =hixProject= shell =buildInputs=:
#+begin_src nix
            hixProject =
              final.haskell-nix.hix.project {
                src = ./.;
                evalSystem = "aarch64-darwin";
                shell = {
                  tools = {
                    haskell-language-server = {};
                  };
                  # Add Elm tools to your dev shell
                  buildInputs = with final.elmPackages; [
                    elm
                    elm-format
                    elm-language-server
                  ];
                };
              };
#+end_src

2. Add the =elm= compiler to the =nativeBuildInputs= of your =frontend= derivation:
#+begin_src nix
        frontend = pkgs.buildNpmPackage {
          pname = "frontend";
          version = "0.1.0";
          src = ./frontend;
          npmDepsHash = "sha256-ISmmvj/aBSrMEJ6fbHP4cGN24JjEHEdqfXlh272HHXk=";

          # Add Elm so npm/vite/webpack can use it during the build
          nativeBuildInputs = [ pkgs.elmPackages.elm ];

          installPhase = ''
            mkdir -p $out/dist
            cp -r dist/* $out/dist/
          '';
        };
#+end_src
* development environment

I'm using nix to set up a development environment




* misc

** TODO explain how to get nix to work with emacs so that it gets the correct compilation tools
** TODO add results to events

- [ ] backend
  - [ ] schedule pipeline to process results
  - [ ] download and store results for event
  - [ ] file storage for unstructured data
  - [ ] file storage for parsed data as csv
  - [ ] table or query layer for api access
- [ ] frontend
  - [ ] get results if event has occourd and results available
  - [ ] summary show place on main screen: class, course, and place
  - [ ] event detail show all results for single race
  - [ ] series show all results for series
  - [ ] performance show chart of corrected time behind


*** Top level path

I have decided to use the URL as the basis for the location for storing source files. This results in a direct relation between the location of the source data and the location of the local data. Maybe I can add a configuration value to modify this if it results in weird path names.

<host>/<url path>/<url filename>

*** Unstructured / source data

Using the filename provided by the url. Will need to figure something out if there is no file name. Also need some way of identifying the filename for the results.

*** Semistructured / parsed data

undecided. for now will use same filename with .csv extension

*** Database

Do I need a database?

- [ ] ingest to table that matches csv file
- [ ] clean to fix data types and handle cases like DNC in place column
- [ ] common table with normalized result format

*** download event

Should have list of events with start dates and finish time

When event has completed poll for results until available or stop after some limit

process data and update state of event

** TODO configuration management

- download location

** TODO document adding a haskell dependency

- add to build-depends in crewd.cabal
- re-trigger nix develop

Create directory for downloading results. Use the URL as a guide for directory and file naming.


* 2026 Schedule
#+name: 2026-schedule
| regatta     | series | start_date | race | class |
|-------------+--------+------------+------+-------|
| Ballard Cup | III    | 2026-07-27 |    1 |     8 |
| Ballard Cup | III    | 2026-08-03 |    2 |     8 |
| Ballard Cup | III    | 2026-08-10 |    3 |     8 |
| Ballard Cup | III    | 2026-08-17 |    4 |     8 |
| Ballard Cup | III    | 2026-08-24 |    5 |     8 |
| Ballard Cup | III    | 2026-08-31 |    6 |     8 |

* Building

** Literate Programming

I'm using  literate programming as much as possible. This means that the program source is generated from an org file using org tangle.

** Build toolchain

The build toolchain is provisioned using a nix flake that is defined in the top level of the directory.

** Frontend

*** TODO reimplement dependencies using nix

Configuration for building node.
#+begin_src nix
  frontend = pkgs.buildNpmPackage {
    pname = "frontend";
    version = "0.1.0";
    src = ./windward-racing;
    npmDepsHash = "sha256-ISmmvj/aBSrMEJ6fbHP4cGN24JjEHEdqfXlh272HHXk=";
    installPhase = ''
      mkdir -p $out/dist
      cp -r dist/* $out/dist/
    '';
  };
#+end_src

Had to add frontend to flake

#+name: add-frontend-to-flake
#+begin_src nix
  inherit frontend;
#+end_src

No I'm getting an error. I think this is because I hacked a =schedule.js= file and have since deleted it. I can change this to either generate the schedule.js file or have the frontend pull the schedule from the server.

Either I need to fallback to using the =./data/schedule.js= hack or refactor the frontend to get the schedule from the server.

#+begin_example
 npm run build

> windward-racing@0.0.0 build
> vite build

vite v8.2.1 building client environment for production...
✓ 16 modules transformed.
✗ Build failed in 39ms
error during build:
Build failed with 1 error:

[UNRESOLVED_IMPORT] Could not resolve './data/schedule.js' in src/App.jsx
   ╭─[ src/App.jsx:3:31 ]
   │
 3 │ import { SCHEDULE_DATA } from "./data/schedule.js";
   │                               ──────────┬─────────
   │                                         ╰─────────── Module not found.
   │
   │ Help: 'src/App.jsx' is imported by the following path:
   │         - src/App.jsx
   │         - src/main.jsx
   │         - index.html
───╯

    at aggregateBindingErrorsIntoJsError (file:///Users/gdowding/git/github/gdowding/crewd/windward-racing/node_modules/rolldown/dist/shared/error-BzLGqhSQ.mjs:48:18)
    at unwrapBindingResult (file:///Users/gdowding/git/github/gdowding/crewd/windward-racing/node_modules/rolldown/dist/shared/error-BzLGqhSQ.mjs:18:128)
    at #build (file:///Users/gdowding/git/github/gdowding/crewd/windward-racing/node_modules/rolldown/dist/shared/rolldown-I5b6h5Km.mjs:132:34)
    at async buildEnvironment (file:///Users/gdowding/git/github/gdowding/crewd/windward-racing/node_modules/vite/dist/node/chunks/node.js:33730:66)
    at async Object.build (file:///Users/gdowding/git/github/gdowding/crewd/windward-racing/node_modules/vite/dist/node/chunks/node.js:34150:19)
    at async Object.buildApp (file:///Users/gdowding/git/github/gdowding/crewd/windward-racing/node_modules/vite/dist/node/chunks/node.js:34147:153)
    at async CAC.<anonymous> (file:///Users/gdowding/git/github/gdowding/crewd/windward-racing/node_modules/vite/dist/node/cli.js:776:3) {
  errors: [Getter/Setter]
}
#+end_example

** Backend

The backend is implemented in Haskell. Haskell dependencies are declared in crewd.cabal. Nix fetches and compiles them through some interaction with cabal (not totaly sure on that)

** Build and run

1. Set up nix environment
   This will provision the build tools. I also use direnv with the =use flake= directive wich manages the environment. I also use envrc-mode in emacs which keeps it syncronized with the nix environment.

   #+begin_example
   nix develop
   #+end_example

2. Generate =src/crewd.hs=. Open =crewd.org= in emacs. Run the tangle command "C-c C-v t". This will tangle =crewd.org= into =src/crewd.hs=

3. Build haskell

   1. Build with cabal
      #+begin_example
      cabal build
      #+end_example

   2. Build with nix
      #+begin_example
      nix build .#crewd:exe:crewd
      #+end_example

4. Running

   1. Run with cabal
      #+begin_example
      cabal run
      #+end_example

   2. Run with nix
      #+begin_example
      nix run .#crewd:exe:crewd
      #+end_example


* deployment

** set up deploy through push

- backend server
- implement frontend in haskell?

*** frontend
Current frontend is Ract + Vite. This is all pretty much generated by AI

It is deployed to vercel

https://vercel.com/irie2

I have connected the github repo to vercel

Looks like there is a way to connect a database to vercel as well. Not sure if that is really needed or not.

*** Database
supabase

https://supabase.com/dashboard/org/olbomtdfdiaahnwfzgfj

can get connectio string here https://supabase.com/dashboard/project/gzhojmodmhyutkcyqkos/integrations/vault/overview?showConnect=true&connectTab=direct


*** backend

If I stick with haskell, it looks like I need to build a container. I can build it with nix

Options for deploying using docker

- railway
- koyeb
- google cloud run


Another option is to set up a VM server and install to that

*** combine frontend and backend on single server

Right now the frontend only gets data from the database. It does not call any server APIs. In theory could just have the backend do updates to the database.

* haskell

** extracting value from either

In haskell, I am calling a function that returns an Either. How do I propegate the error if it is a Left or access the data if it is a Right?

#+begin_reasoning
**Defining the Strategy**

Okay, I'm now zeroing in on the core challenge: handling the `Either` type in Haskell. The goal is clear - either pass on the `Left` (error) or extract the `Right` (value). This is where the real work begins, and I am beginning to devise potential approaches.


**Evaluating the Techniques**

I am now comparing different solutions for dealing with the `Either` type in Haskell. I've considered monadic binding (`do` notation) as the most idiomatic option, and pattern matching for explicit control. I'm focusing on concisely presenting both the `do` notation and the `case` statement to illustrate the two methods. I am now also considering a scenario where the surrounding function might also return `Either e a`.



#+end_reasoning

The most idiomatic way is using *=do= notation*. Since =Either= is a Monad, using =<-= will automatically extract the =Right= value or short-circuit and propagate the =Left= error.

/(Note: Your enclosing function must also return an =Either= with the same error type)./

#+begin_src haskell
myFunction :: Either String Int
myFunction = do
  val <- functionReturningEither  -- extracts Right, or immediately returns Left
  return (val + 1)
#+end_src

If you need explicit control (or if your enclosing function returns a different type), use *pattern matching* with a =case= expression:

#+begin_src haskell
myFunction :: Either String Int
myFunction =
  case functionReturningEither of
    Left err  -> Left err          -- propagate error
    Right val -> Right (val + 1)   -- access and use data
#+end_src

For simple transformations of the =Right= value while automatically passing =Left= through, you can use =fmap= (or =<$>=):

#+begin_src haskell
myFunction :: Either String Int
myFunction = (+ 1) <$> functionReturningEither
#+end_src
How do I extract the value
