load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "graph",
    srcs = [
        "prelude.generated.go",
        "race.generated.go",
        "resolver.go",
        "root.generated.go",
        "root.resolvers.go",
        "root_.generated.go",
        "schedule.generated.go",
        "schedule.resolvers.go",
        "series.generated.go",
        "series.resolvers.go",
    ],
    importpath = "github.com/gdowding/crewd/graph",
    visibility = ["//visibility:public"],
    deps = [
        "//graph/model",
        "@com_github_99designs_gqlgen//graphql",
        "@com_github_99designs_gqlgen//graphql/introspection",
        "@com_github_vektah_gqlparser_v2//:gqlparser",
        "@com_github_vektah_gqlparser_v2//ast",
    ],
)
