package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/gdowding/crewd/graph/database"
	"github.com/gdowding/crewd/graph/model"
	"github.com/google/uuid"
)

// CreateSchedule is the resolver for the createSchedule field.
func (r *mutationResolver) CreateSchedule(ctx context.Context, input *model.NewSchedule) (*model.Schedule, error) {
	id := uuid.New().String()
	schedule := &model.Schedule{
		ID:     id,
		Name:   input.Name,
		Series: []*model.Series{},
	}
	if err := database.DB.Create(schedule).Error; err != nil {
		return nil, err
	}
	return schedule, nil
}

// CreateSeries is the resolver for the createSeries field.
func (r *mutationResolver) CreateSeries(ctx context.Context, input *model.NewSeries) (*model.Series, error) {
	id := uuid.New().String()
	series := model.Series{
		ID:         id,
		ScheduleID: input.ScheduleID,
		Name:       input.Name,
	}
	if err := database.DB.Create(series).Error; err != nil {
		return nil, err
	}
	// schedule.Series = append(schedule.Series, &series)
	// change dependencies to be references then remove this line.
	// r.Schedules_[input.ScheduleID] = schedule
	return &series, nil
}

// CreateRace is the resolver for the createRace field.
func (r *mutationResolver) CreateRace(ctx context.Context, input *model.NewRace) (*model.Race, error) {
	id := uuid.New().String()
	race := model.Race{
		ID:       id,
		Name:     input.Name,
		SeriesID: input.SeriesID,
	}
	if err := database.DB.Create(race).Error; err != nil {
		return nil, err
	}
	return &race, nil
}

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context) ([]*model.Schedule, error) {
	var schedules []*model.Schedule
	if err := database.DB.Find(&schedules).Error; err != nil {
		return nil, err
	}
	return schedules, nil
}

// Series is the resolver for the series field.
func (r *queryResolver) Series(ctx context.Context) ([]*model.Series, error) {
	var series []*model.Series
	if err := database.DB.Find(&series).Error; err != nil {
		return nil, err
	}
	return series, nil
}

// Races is the resolver for the races field.
func (r *queryResolver) Races(ctx context.Context) ([]*model.Race, error) {
	panic(fmt.Errorf("not implemented: Races - races"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
