package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"crypto/rand"
	"fmt"
	"math/big"

	"github.com/gdowding/crewd/graph/model"
)

// CreateSchedule is the resolver for the createSchedule field.
func (r *mutationResolver) CreateSchedule(ctx context.Context, input *model.NewSchedule) (*model.Schedule, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	schedule := &model.Schedule{
		ID:   fmt.Sprintf("T%d", randNumber),
		Name: input.Name,
	}
	r.schedules = append(r.schedules, schedule)
	return schedule, nil
}

// CreateSeries is the resolver for the createSeries field.
func (r *mutationResolver) CreateSeries(ctx context.Context, input *model.NewSeries) (*model.Series, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	series := &model.Series{
		ID:   fmt.Sprintf("T%d", randNumber),
		Name: input.Name,
	}
	r.series = append(r.series, series)
	return series, nil
}

// CreateRace is the resolver for the createRace field.
func (r *mutationResolver) CreateRace(ctx context.Context, input *model.NewRace) (*model.Race, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	race := &model.Race{
		ID:   fmt.Sprintf("T%d", randNumber),
		Name: input.Name,
		Series: &model.Series{
			ID:   input.SeriesID,
			Name: "series " + input.SeriesID,
		},
	}
	r.races = append(r.races, race)
	return race, nil
}

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context) ([]*model.Schedule, error) {
	return r.schedules, nil
}

// Series is the resolver for the series field.
func (r *queryResolver) Series(ctx context.Context) ([]*model.Series, error) {
	panic(fmt.Errorf("not implemented: Series - series"))
}

// Races is the resolver for the races field.
func (r *queryResolver) Races(ctx context.Context) ([]*model.Race, error) {
	panic(fmt.Errorf("not implemented: Races - races"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
