package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/gdowding/crewd/graph/model"
)

// Series is the resolver for the series field.
func (r *scheduleResolver) Series(ctx context.Context, obj *model.Schedule) ([]*model.Series, error) {
	var series []*model.Series
	for _, s := range r.series {
		if obj.ID == s.Schedule.ID {
			series = append(series, s)
		}
	}
	return series, nil
}

// Schedule returns ScheduleResolver implementation.
func (r *Resolver) Schedule() ScheduleResolver { return &scheduleResolver{r} }

type scheduleResolver struct{ *Resolver }
