package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/gdowding/crewd/graph/database"
	"github.com/gdowding/crewd/graph/model"
	"gorm.io/gorm"
)

// Schedule is the resolver for the schedule field.
func (r *seriesResolver) Schedule(ctx context.Context, obj *model.Series) (*model.Schedule, error) {
	schedule, err := gorm.G[model.Schedule](database.DB).Where("id = ?", obj.ScheduleID).First(ctx)
	if err != nil {
		return nil, err
	}
	return &schedule, nil
}

// Series returns SeriesResolver implementation.
func (r *Resolver) Series() SeriesResolver { return &seriesResolver{r} }

type seriesResolver struct{ *Resolver }
