package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/gdowding/crewd/graph/model"
)

// Schedule is the resolver for the schedule field.
func (r *seriesResolver) Schedule(ctx context.Context, obj *model.Series) (*model.Schedule, error) {
	var schedule *model.Schedule

	for _, s := range r.Schedules_ {
		if obj.ScheduleID == s.ID {
			schedule = &s
			break
		}
	}
	if schedule == nil {
		return nil, fmt.Errorf("unable to find schedule with ID: %s", obj.ScheduleID)
	}
	return schedule, nil
}

// Series returns SeriesResolver implementation.
func (r *Resolver) Series() SeriesResolver { return &seriesResolver{r} }

type seriesResolver struct{ *Resolver }
