load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "ent",
    srcs = [
        "client.go",
        "ent.go",
        "mutation.go",
        "runtime.go",
        "schedule.go",
        "schedule_create.go",
        "schedule_delete.go",
        "schedule_query.go",
        "schedule_update.go",
        "tx.go",
    ],
    importpath = "github.com/gdowding/crewd/ent/ent",
    visibility = ["//visibility:public"],
    deps = [
        "//ent/ent/migrate",
        "//ent/ent/predicate",
        "//ent/ent/schedule",
        "@io_entgo_ent//:ent",
        "@io_entgo_ent//dialect",
        "@io_entgo_ent//dialect/sql",
        "@io_entgo_ent//dialect/sql/sqlgraph",
        "@io_entgo_ent//schema/field",
    ],
)
