load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "schedule",
    srcs = [
        "schedule.go",
        "where.go",
    ],
    importpath = "github.com/gdowding/crewd/ent/ent/schedule",
    visibility = ["//visibility:public"],
    deps = [
        "//ent/ent/predicate",
        "@io_entgo_ent//dialect/sql",
    ],
)
