* <2026-01-17 Sat>
** I need to make a shareable calendar for upcoming races
*** TODO add dock time
*** TODO add time limit
*** TODO add rsvp
* <2026-01-19 Mon>
Change of direction

Instead of finding libraries that meet my needs and adapting to them, I am thinking I will make more progress and enjoy this more if I am working direcly on the code. I realized that using a database, an ORM and a querying library is taking time away from working on the business logic. I can use tools like emacs org-mode for the management UI, the file system for storage, google sheets/calendar for user UI.

I need to be able to.

- read in from file system using structure to manage series and race relationships
- parse the org format being used in management UI files
- read in crew list from sheets
- read in ics from calendar for invit responses
- read in csv from sheets for sign ups
- merge data from org and sheets
  - figure out what data can come from calendar and sheets
    - sign ups
- output calendar ics
- output csv for sheets
  - complete schedule
  - indivdual races

** TODO read in filesystem and store in internal data structure
- used gemini to generate program to read data into memory

* <2026-01-22 Thu>
** TODO get something to production
- [ ] Get happy with output columns
- [ ] output to csv and upload to spreadsheet
*** columns
- date start
- date end if different that date start
- dock time
- sponsor
- series
- race
* <2026-02-04 Wed>
** TODO read file and display in window
* <2026-02-05 Thu>
** was able to call for data on server and display
** update call to server to get vector of data and display
SCHEDULED: <2026-02-05 Thu>
Stuck on getting the data from the server. Compiler error where the rendering is suppose to happen.

This is a little covoluted, but it looks like when it gets to e.name, e should be an element in the vector not the whole vector. Maybe I need to verify the get_events function.


#+begin_src rust
	<Suspense
	    fallback= move || view! {<p>"Loading..."</p>}
	>
	{move || events_r.get().map(|es| {
	    es.into_iter().map(|e| {
		 view!{ <li>{e.name}</li> }
	     }).collect_view()
	 })}
	    </Suspense>
#+end_src

#+begin_example
error[E0609]: no field `name` on type `Vec<app::Event>`
   --> src/app.rs:149:18
    |
149 |          view!{ <li>{e.name}</li> }
    |                        ^^^^ unknown field
#+end_example


Some findings

- iter can operate on an Option. It will return either Some or None depending on the contents of the option.
- some things have IntoView trait like Option, Result, and String. That is why simply returning a string "just works".
- if using a match, all branches need to produce the same result. Use r.into_any() for different types of views since each element is its own view type.
- not sure why I was getting unknown field above. Not sure it matters now.
- would prefer if iter only worked on sequences not enums
- would prefer to opt into the convenience of IntoView trait automatically working for String when calling server_function
