schedule {
  name
  events
}

schedule.events -> event {
target-arrowhead: *
}

event {
  series
  race
  delivery
  maintenence
}


boat

series {
  sign up open
  sign up deadline
  events
}

race {
  start time
  time limit
  crew
  sign up open
  sign up deadline
}

crew
