load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "schedule",
    srcs = ["schedule.go"],
    importpath = "github.com/gdowding/crewd/internal/cli/schedule",
    visibility = ["//visibility:public"],
    deps = [
        "//ent/ent",
        "//ent/ent/schedule",
        "//internal/cli",
        "@com_github_spf13_cobra//:cobra",
    ],
)
