// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewRace struct {
	Name     string `json:"name"`
	SeriesID string `json:"seriesId"`
}

type NewSchedule struct {
	Name string `json:"name"`
}

type NewSeries struct {
	Name       string `json:"name"`
	ScheduleID string `json:"scheduleID"`
}

type Query struct {
}

type Race struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Series *Series `json:"series"`
}
