load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "ent",
    srcs = ["generate.go"],
    importpath = "github.com/gdowding/crewd/ent",
    visibility = ["//visibility:public"],
)

# genrule(
#     name = "generate",
#     srcs = [
#         "generate.go",
#         "schema/schedule.go",
#         "//:go_mod",
#     ],
#     outs = [
#         "client.go",
#         "ent.go",
#         "enttest/enttest.go",
#         "hook/hook.go",
#         "migrate/migrate.go",
#         "migrate/schema.go",
#         "mutation.go",
#         "predicate/predicate.go",
#         "runtime/runtime.go",
#         "schedule/schedule.go",
#         "schedule/schedule_create.go",
#         "schedule/schedule_delete.go",
#         "schedule/schedule_query.go",
#         "schedule/schedule_update.go",
#         "schedule/where.go",
#         "tx.go",
#     ],
#     #cmd = "which go >env.txt && exit 1", #
#     cmd = "go run -mod=mod entgo.io/ent/cmd/ent generate ./ent/schema",
#     tools = ["@io_entgo_ent//:ent"],
# )
