load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cmd",
    srcs = ["root.go"],
    importpath = "github.com/gdowding/crewd/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/cli",
        "//internal/cli/schedule",
        "@com_github_spf13_cobra//:cobra",
    ],
)
